name: ticketer-dev

services:
  postgres:
    container_name: t-postgres
    image: postgres:16
    environment:
      - POSTGRES_DB=ticketer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5551:5432
    volumes:
      - ./.ticketer/postgres:/var/lib/postgresql/data
    restart: always
    shm_size: 128mb
